version: "3.8"
services:
  backend:
    build: ./backend
    container_name: ai-backend
    environment:
      - HF_MODEL=${HF_MODEL:-distilbert-base-uncased-finetuned-sst-2-english}
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: ai-frontend
    environment:
      - BACKEND_URL=http://backend:8000/predict
    ports:
      - "5000:5000"
    depends_on:
      - backend
    restart: always
