- hosts: ai_vm
  become: yes
  tasks:
    # 1. Install Docker, Git, and Python PIP (for docker-compose)
    - name: Update apt and install packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - docker.io
          - git
…      args:
        executable: /bin/bash
      become: no

# --- HANDLERS (Used to gracefully reboot after adding the user to the docker group) ---
  handlers:
    - name: Reboot and Wait
      ansible.builtin.reboot:
        reboot_timeout: 300